queue_rules:
  - name: duplicated default from Auto Rebase and Merge
    queue_conditions:
      - base=master
      - status-success=ci
      - 'label=ready to squash and merge'
      - base=master
      - status-success=ci
      - 'label=ready to rebase and merge'
    merge_conditions: []
    merge_method: squash
  - name: default
    queue_conditions:
      - base=master
      - status-success=ci
      - 'label=ready to squash and merge'
    merge_conditions:
      - check-success=ci
    merge_method: squash

pull_request_rules:
  - name: Auto Squash and Merge
    conditions:
      - base=master
      - status-success=ci
      - 'label=ready to squash and merge'
    actions:
      delete_head_branch: {}
  - name: Auto Rebase and Merge
    conditions:
      - base=master
      - status-success=ci
      - 'label=ready to rebase and merge'
    actions:
      delete_head_branch: {}
  - name: Auto Rebase and Merge + Auto Squash and Merge
    conditions: []
    actions:
      queue:
